### ISSUE TITLE
Content Security Policy (and other headers)

### ISSUE THREAD

**Issue by Dutchy-** [TuinfeesT/PicAxe#1]
We want to add the Content Security Policy in the app, rather than setting it in the webserver, to make a secure installation easier.

However, existing solutions require setting the header per view/response, e.g.
http://stackoverflow.com/questions/14956085/django-add-response-header-when-using-render-to-response
https://github.com/mozilla/django-csp

Todo: investigate how to set headers globally.

**Comment by akaIDIOT** [comment]
[Docs for django-csp](http://django-csp.readthedocs.org/en/latest/installation.html) say it has defaults:

```
MIDDLEWARE_CLASSES = (
    # ...
    'csp.middleware.CSPMiddleware',
    # ...
)
```

What it will include by default is [configurable](http://django-csp.readthedocs.org/en/latest/configuration.html#policy-settings); would that satisfy our requirements?
